# Reading In Files

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("countries of the world.csv")
df.head()

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [8]:
df.iloc[(df["Country"].str.contains("A")) & df["Region"].str.contains("C"),:]

                   Country                               Region
2                 Algeria   NORTHERN AFRICA
3          American Samoa   OCEANIA
5                  Angola   SUB-SAHARAN AFRICA
6                Anguilla               LATIN AMER. & CARIB
7       Antigua & Barbuda               LATIN AMER. & CARIB
8               Argentina               LATIN AMER. & CARIB
9                 Armenia                  C.W. OF IND. STATES
10                  Aruba               LATIN AMER. & CARIB
11              Australia   OCEANIA
13             Azerbaijan                  C.W. OF IND. STATES
39   Central African Rep.   SUB-SAHARAN AFRICA
147  Netherlands Antilles               LATIN AMER. & CARIB
189          South Africa   SUB-SAHARAN AFRICA

In [11]:
#df = pd.read_csv(r"C:\Users\alexf\OneDrive\Documents\Pandas Tutorial\countries of the world.txt", sep = '\t')
#df

#df = pd.read_table("countries of the world.csv")
df = pd.read_table("countries of the world.csv", sep = ',')

df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [12]:
df = pd.read_json("json_sample.json")
df

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [13]:
df2 = pd.read_excel("world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df2

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

In [14]:
pd.set_option('display.max.rows', 235)
pd.set_option('display.max.columns', 40)

In [15]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    str
 2   Country  234 non-null    str
 3   Capital  234 non-null    str
dtypes: int64(1), str(3)
memory usage: 7.4 KB

In [26]:
df2.shape

(234, 4)

In [28]:
df2.head(10)

   Rank CCA3              Country           Capital
0    36  AFG          Afghanistan             Kabul
1   138  ALB              Albania            Tirana
2    34  DZA              Algeria           Algiers
3   213  ASM       American Samoa         Pago Pago
4   203  AND              Andorra  Andorra la Vella
5    42  AGO               Angola            Luanda
6   224  AIA             Anguilla        The Valley
7   201  ATG  Antigua and Barbuda    Saint Johnâ€™s
8    33  ARG            Argentina      Buenos Aires
9   140  ARM              Armenia           Yerevan

In [29]:
df2.tail(10)

     Rank CCA3            Country       Capital
224    43  UZB         Uzbekistan      Tashkent
225   181  VUT            Vanuatu     Port-Vila
226   234  VAT       Vatican City  Vatican City
227    51  VEN          Venezuela       Caracas
228    16  VNM            Vietnam         Hanoi
229   226  WLF  Wallis and Futuna      Mata-Utu
230   172  ESH     Western Sahara     El AaiÃºn
231    46  YEM              Yemen         Sanaa
232    63  ZMB             Zambia        Lusaka
233    74  ZWE           Zimbabwe        Harare

In [16]:
df2['Rank'].head()

0     36
1    138
2     34
3    213
4    203
Name: Rank, dtype: int64

In [20]:
df2 = df2.set_index("Country")
df2.loc['Uzbekistan']

Rank             43
CCA3            UZB
Capital    Tashkent
Name: Uzbekistan, dtype: object

In [21]:
df2.iloc[224]

Rank             43
CCA3            UZB
Capital    Tashkent
Name: Uzbekistan, dtype: object