# Data Cleaning in Pandas

In [115]:
import pandas as pd

In [116]:
df = pd.read_excel("Customer Call List.xlsx")
print(df.head())

df[df.duplicated(keep=False)]

   CustomerID First_Name Last_Name  Phone_Number  \
0        1001      Frodo   Baggins  123-545-5421
1        1002       Abed     Nadir  123/643/9775
2        1003     Walter    /White    7066950392
3        1004     Dwight   Schrute  123-543-2345
4        1005        Jon      Snow  876|678|3469

                                 Address Paying Customer Do_Not_Contact  \
0                  123 Shire Lane, Shire             Yes             No
1                    93 West Main Street              No            Yes
2                     298 Drugs Driveway               N            NaN
3  980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                       123 Dragons Road               Y             No

   Not_Useful_Column
0               True
1              False
2               True
3               True
4               True

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [117]:
df[df.duplicated()]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [118]:
df[df["Last_Name"] == "Skywalker"]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [119]:
df = df.drop_duplicates()

In [120]:
df.groupby("Do_Not_Contact")["CustomerID"].count()

Do_Not_Contact
N      3
No     9
Y      1
Yes    3
Name: CustomerID, dtype: int64

In [121]:
df.shape

(20, 8)

In [122]:
df = df.drop_duplicates()
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [123]:
#0,1,2,3,4,5.   only include 3 and 4.  5 is excluded
df.iloc[:,3:5].head()

   Phone_Number                                Address
0  123-545-5421                  123 Shire Lane, Shire
1  123/643/9775                    93 West Main Street
2    7066950392                     298 Drugs Driveway
3  123-543-2345  980 Paper Avenue, Pennsylvania, 18503
4  876|678|3469                       123 Dragons Road

In [124]:
df.drop(columns = ["Not_Useful_Column", "Phone_Number"]).head()

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,93 West Main Street,No,Yes
2,1003,Walter,/White,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,123 Dragons Road,Y,No

In [125]:
df.iloc[:,df.columns.str.contains("n")].head()

   Phone_Number Paying Customer Do_Not_Contact  Not_Useful_Column
0  123-545-5421             Yes             No               True
1  123/643/9775              No            Yes              False
2    7066950392               N            NaN               True
3  123-543-2345             Yes              Y               True
4  876|678|3469               Y             No               True

In [126]:
df.loc[:, df.columns.str.contains("n")].head()

   Phone_Number Paying Customer Do_Not_Contact  Not_Useful_Column
0  123-545-5421             Yes             No               True
1  123/643/9775              No            Yes              False
2    7066950392               N            NaN               True
3  123-543-2345             Yes              Y               True
4  876|678|3469               Y             No               True

In [127]:
df.loc[:, df.columns.str.contains(r"[nL]")].head()

  Last_Name  Phone_Number Paying Customer Do_Not_Contact  Not_Useful_Column
0   Baggins  123-545-5421             Yes             No               True
1     Nadir  123/643/9775              No            Yes              False
2    /White    7066950392               N            NaN               True
3   Schrute  123-543-2345             Yes              Y               True
4      Snow  876|678|3469               Y             No               True

In [128]:
df["Last_Name"].str.lstrip(".../").head(21)

0         Baggins
1           Nadir
2           White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: str

In [129]:
#df["Last_Name"] = 
#df["Last_Name"] = df["Last_Name"].str.lstrip("/")
#df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df["Last_Name"] = df["Last_Name"].str.strip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [130]:
#df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

#df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

#df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

#df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')

df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [131]:
df["Phone_Number"].fillna('')

0     123-545-5421
1     123/643/9775
2
3     123-543-2345
4     876|678|3469
5     304-762-2467
6
7     876|678|3469
8              N/a
9     123-545-5421
10
11
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [132]:
#2 is the maximum number of splits per string 
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',', n=2, expand=True)
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,NaN,NaN
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,123 Dragons Road,NaN,NaN

In [133]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].fillna('')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,NaN,NaN
2,1003,Walter,White,NaN,298 Drugs Driveway,N,,True,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,,False,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,,True,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Y,True,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,NaN

In [134]:
#df = df.replace('N/a','')
#df = df.replace('NaN','')

df=df.fillna('')
df["Phone_Number"] = df["Phone_Number"].str.replace('N/a','')
df["Phone_Number"] = df["Phone_Number"].str.replace('NaN','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,

In [135]:
#if you simply assign them, they will remain linked
df2 = df.copy()

In [136]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [137]:
df.loc[df.index.values,:]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,

`inplace = True` : makes the changes to df in memeory and do not return a new df

In [138]:
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,

In [ ]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)
df

#Another way to drop null values
#df = df.dropna(subset="Phone_Number"), inplace=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,

In [144]:
df2.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,

In [146]:
df2.loc[(df2["Do_Not_Contact"]=="Y")  & (df2["Last_Name"] == "Nadir"),:]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,,

In [148]:
df3 = df2[df2["Do_Not_Contact"].isin(["Y","N"])]
df3

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,

In [149]:
# after you filter you need to reset the index
df3 = df3.reset_index(drop=True)
df3

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,,
2,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
3,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
4,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,,
5,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
6,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
8,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
9,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
10,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
11,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
12,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
13,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
14,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,,
15,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,