# Indexing

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("world_population.csv")

df.head()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [31]:
df.groupby("Continent").agg({"Growth Rate":["sum","min","max"]})

              Growth Rate
                      sum     min     max
Continent
Africa            57.1861  1.0004  1.0378
Asia              50.4692  0.9816  1.0376
Europe            50.1128  0.9120  1.0691
North America     39.1671  0.9937  1.0150
Oceania           23.1698  0.9831  1.0238
South America     14.1114  0.9990  1.0239

In [32]:
my_continent = ["Asia","Europe"]
df[df["Continent"].isin(my_continent)].head()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
9,140,ARM,Armenia,Yerevan,Asia,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
12,99,AUT,Austria,Vienna,Europe,8939617.0,8907777.0,8642421.0,8362829.0,8010428.0,7678729.0,7547561.0,7465301.0,83871.0,106.5877,1.0020,0.11

In [3]:
df2 = df.set_index("Country")
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [8]:
df2.filter(items = ["Albania"], axis =0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04

In [10]:
df = pd.read_csv("world_population.csv", index_col = "Country")

df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [11]:
df.reset_index(inplace=True)

In [12]:
df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

- `df.set_index('Country', inplace=True)`

- `set_index('Country')`

Takes the column named 'Country' and makes it the row index (the labels on the left).
That column is removed from the columns and used as the index instead.
Other columns stay as columns; only which values identify each row changes.

- `inplace=True`

Tells pandas to change df itself instead of returning a new DataFrame.
After the call, df is updated; you don’t assign the result to a variable.
With inplace=False (the default), you’d get a new DataFrame and the original df would be unchanged unless you did df = df.set_index('Country').
Example

Before: index might be 0, 1, 2, ... and there’s a Country column.

- After `df.set_index('Country', inplace=True)`:

Rows are labeled by country name (e.g. "Albania", "France").
There is no longer a separate Country column.
That’s why operations like df.filter(items=["Albania"], axis=0) work when "Albania" is an index label after you’ve set the index to country.

In [13]:
df2 = df.set_index('Country')

df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [22]:
df2.filter(items = ["Albania"], axis =0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04

In [23]:
df2.loc['Albania']

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [39]:
df.iloc[1]

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [40]:
df.reset_index(inplace = True)

In [24]:
df.set_index(['Continent','Country'], inplace=True)

In [42]:
df.sort_index().head(20)

#pd.set_option('display.max.rows', 235)

                                    Rank CCA3      Capital  2022 Population  \
Continent Country
Africa    Algeria                     34  DZA      Algiers       44903225.0
          Angola                      42  AGO       Luanda       35588987.0
          Benin                       77  BEN   Porto-Novo       13352864.0
          Botswana                   144  BWA     Gaborone        2630296.0
          Burkina Faso                58  BFA  Ouagadougou       22673762.0
          Burundi                     78  BDI    Bujumbura       12889576.0
          Cameroon                    53  CMR      Yaounde       27914536.0
          Cape Verde                 171  CPV        Praia         593149.0
          Central African Republic   117  CAF       Bangui        5579144.0
          Chad                        69  TCD    N'Djamena       17723315.0
          Comoros                    163  COM       Moroni         836774.0
          DR Congo                    15  COD     Kinshasa       99010212.0
          Djibouti                   160  DJI     Djibouti        1120849.0
          Egypt                       14  EGY        Cairo      110990103.0
          Equatorial Guinea          152  GNQ       Malabo        1674908.0
          Eritrea                    132  ERI       Asmara        3684032.0
          Eswatini                   159  SWZ      Mbabane              NaN
          Ethiopia                    12  ETH  Addis Ababa      123379924.0
          Gabon                      146  GAB   Libreville        2388992.0
          Gambia                     142  GMB       Banjul        2705992.0

                                    2020 Population  2015 Population  \
Continent Country
Africa    Algeria                        43451666.0       39543154.0
          Angola                         33428485.0       28127721.0
          Benin                          12643123.0       10932783.0
          Botswana                        2546402.0        2305171.0
          Burkina Faso                   21522626.0       18718019.0
          Burundi                        12220227.0       10727148.0
          Cameroon                       26491087.0       23012646.0
          Cape Verde                       582640.0         552166.0
          Central African Republic        5343020.0        4819333.0
          Chad                           16644701.0       14140274.0
          Comoros                          806166.0         730216.0
          DR Congo                       92853164.0       78656904.0
          Djibouti                        1090156.0        1006259.0
          Egypt                         107465134.0       97723799.0
          Equatorial Guinea               1596049.0              NaN
          Eritrea                         3555868.0        3340006.0
          Eswatini                        1180655.0        1133936.0
          Ethiopia                      117190911.0      102471895.0
          Gabon                           2292573.0        2028517.0
          Gambia                          2573995.0        2253133.0

                                    2010 Population  2000 Population  \
Continent Country
Africa    Algeria                        35856344.0       30774621.0
          Angola                         23364185.0       16394062.0
          Benin                           9445710.0        6998023.0
          Botswana                        2091664.0        1726985.0
          Burkina Faso                   16116845.0       11882888.0
          Burundi                         9126605.0        6307659.0
          Cameroon                       19878036.0       15091594.0
          Cape Verde                       521212.0         458251.0
          Central African Republic        4660067.0        3759170.0
          Chad                           11894727.0        8259137.0
          Comoros                          656024.0         536758.0
          DR Congo                       66391257.0       48616317.0
          Djibouti                         919199.0         742033.0
          Egypt                          87252413.0       71371371.0
          Equatorial Guinea               1094524.0         684977.0
          Eritrea                         3147727.0        2392880.0
          Eswatini                        1099920.0        1030496.0
          Ethiopia                       89237791.0       67031867.0
          Gabon                           1711105.0        1272935.0
          Gambia                                NaN              NaN

                                    1990 Population  1980 Population  \
Continent Country
Africa    Algeria                        25518074.0       18739378.0
          Angola                         11828638.0        8330047.0
          Benin                           5133419.0        3833939.0
          Botswana                        1341474.0         938578.0
          Burkina Faso                    9131361.0        6932967.0
          Burundi                         5483793.0        4312834.0
          Cameroon                       11430520.0        8519891.0
          Cape Verde                       364563.0         317234.0
          Central African Republic        2809221.0        2415276.0
          Chad                            5827069.0        4408230.0
          Comoros                          431119.0         328328.0
          DR Congo                       35987541.0       26708686.0
          Djibouti                         577173.0         324121.0
          Egypt                          57214630.0       43748556.0
          Equatorial Guinea                465549.0         282509.0
          Eritrea                         2149960.0        1657982.0
          Eswatini                         854011.0         598564.0
          Ethiopia                       47878073.0       34945469.0
          Gabon                            983028.0         749078.0
          Gambia                                NaN              NaN

                                    1970 Population  Area (km²)  \
Continent Country
Africa    Algeria                        13795915.0   2381741.0
          Angola                          6029700.0   1246700.0
          Benin                           3023443.0    112622.0
          Botswana                         592244.0    582000.0
          Burkina Faso                    5611666.0    272967.0
          Burundi                         3497834.0     27834.0
          Cameroon                        6452787.0    475442.0
          Cape Verde                       287262.0      4033.0
          Central African Republic        2067356.0    622984.0
          Chad                            3667394.0   1284000.0
          Comoros                          242351.0      1862.0
          DR Congo                       20151733.0   2344858.0
          Djibouti                         144379.0     23200.0
          Egypt                          34781986.0   1002450.0
          Equatorial Guinea                316955.0     28051.0
          Eritrea                         1272748.0    117600.0
          Eswatini                         442865.0     17364.0
          Ethiopia                       28308246.0   1104300.0
          Gabon                            597192.0    267668.0
          Gambia                                NaN     10689.0

                                    Density (per km²)  Growth Rate  \
Continent Country
Africa    Algeria                             18.8531       1.0164
          Angola                              28.5466       1.0315
          Benin                              118.5635       1.0274
          Botswana                             4.5194       1.0162
          Burkina Faso                        83.0641       1.0259
          Burundi                            463.0874       1.0270
          Cameroon                            58.7128       1.0263
          Cape Verde                         147.0739       1.0089
          Central African Republic             8.9555       1.0224
          Chad                                13.8032       1.0316
          Comoros                            449.3953       1.0184
          DR Congo                            42.2244       1.0325
          Djibouti                            48.3125       1.0138
          Egypt                              110.7188       1.0158
          Equatorial Guinea                   59.7094       1.0247
          Eritrea                             31.3268       1.0176
          Eswatini                            69.2047       1.0079
          Ethiopia                           111.7268       1.0257
          Gabon                                8.9252       1.0204
          Gambia                             253.1567       1.0250

                                    World Population Percentage
Continent Country
Africa    Algeria                                          0.56
          Angola                                           0.45
          Benin                                            0.17
          Botswana                                         0.03
          Burkina Faso                                     0.28
          Burundi                                          0.16
          Cameroon                                         0.35
          Cape Verde                                       0.01
          Central African Republic                         0.07
          Chad                                             0.22
          Comoros                                          0.01
          DR Congo                                         1.24
          Djibouti                                         0.01
          Egypt                                            1.39
          Equatorial Guinea                                0.02
          Eritrea                                          0.05
          Eswatini                                         0.02
          Ethiopia                                         1.55
          Gabon                                            0.03
          Gambia                                           0.03

In [29]:
#Continent and Country are index
df.loc[('Africa','Angola')]

Rank                                   42
CCA3                                  AGO
Capital                            Luanda
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: (Africa, Angola), dtype: object

# Why filter gives nothing
- `filter(items=["Africa", "Angola"], axis=0)` looks for row index labels that equal "Africa" or "Angola".
With a MultiIndex, each row’s label is usually a tuple like `("Africa", "Angola")`. 
- That tuple is not the same as the string "Africa" or "Angola", so nothing matches and you get an empty frame.

In [28]:
df.filter(items = ["Africa","Angola"], axis =0)

Empty DataFrame
Columns: [Rank, CCA3, Capital, 2022 Population, 2020 Population, 2015 Population, 2010 Population, 2000 Population, 1990 Population, 1980 Population, 1970 Population, Area (km²), Density (per km²), Growth Rate, World Population Percentage]
Index: []

In [49]:
df.iloc[1]

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: (Europe, Albania), dtype: object